package pathfindercharactergenerator;

import java.awt.*;


public class MainMenuUI extends MyJPanel
{
    Image woodBack = Toolkit.getDefaultToolkit().getImage("images/backgrounds/wood.jpg");
    Image logo = Toolkit.getDefaultToolkit().getImage("images/backgrounds/logo.png");


    
    public MainMenuUI() 
    {
        initComponents();
    }
    
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(woodBack,0,0,this);
        g.drawImage(logo, 200, 50, this);
        
       
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        charCreateButton = new javax.swing.JButton();
        charViewButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));

        charCreateButton.setText("Create A Character");
        charCreateButton.setMaximumSize(new java.awt.Dimension(100, 100));
        charCreateButton.setMinimumSize(new java.awt.Dimension(100, 100));
        charCreateButton.setPreferredSize(new java.awt.Dimension(100, 100));
        charCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charCreateButtonActionPerformed(evt);
            }
        });

        charViewButton.setText("View a Character");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(charCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addComponent(charViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void charCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charCreateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton charCreateButton;
    public javax.swing.JButton charViewButton;
    // End of variables declaration//GEN-END:variables
}
